AppView/Controllers/AccessController.cs
using AppData.DBContext;
using AppData.Models;
using Microsoft.AspNetCore.Mvc;

namespace AppView.Controllers
{
    public class AccessController : Controller
    {
        private readonly ILogger<AccessController> _logger;
        BookShopDbContext _dbContext;
        HttpClient http;

        public AccessController(ILogger<AccessController> logger)
        {
            _logger = logger;
            http = new HttpClient();
            _dbContext = new BookShopDbContext();
        }

        [HttpGet]
        public IActionResult Login()
        {
            if (HttpContext.Session.GetString("Email") == null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]

        public IActionResult Login(User user)
        {
            if (HttpContext.Session.GetString("Email") == null)
            {
                var u = _dbContext.users.Where(x => x.Email.Equals(user.Email) && x.Password.Equals(user.Password)).FirstOrDefault();
                if (u != null)
                {
                    HttpContext.Session.SetString("Email", u.Email);
                    var role = _dbContext.userRoles.FirstOrDefault(x => x.RoleId == u.RoleId);
                    HttpContext.Session.SetString("UserId", u.UserId.ToString());
                    HttpContext.Session.SetString("UserName", u.Name);
                    HttpContext.Session.SetString("UserRole", role.RoleName);
                    return RedirectToAction("Index", "Home");
                }

            }
            return BadRequest("Đăng nhập thất bại!");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            HttpContext.Session.Remove("UserId");
            HttpContext.Session.Remove("Email");
            HttpContext.Session.Remove("UserName");
            HttpContext.Session.Remove("UserRole");
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(User user)
        {
            var lstUsers = _dbContext.users.ToList();
            foreach (var x in lstUsers)
            {
                if (x.Email == user.Email)
                {
                    return BadRequest("Email đã được sử dụng!");
                }
            }

            if (String.IsNullOrEmpty(user.Email) || String.IsNullOrEmpty(user.Password) || String.IsNullOrEmpty(user.Name) || String.IsNullOrEmpty(user.PhoneNumber))
            {
                return View();
            }

            // Add new User
            user.UserId = Guid.NewGuid();
            user.RoleId = _dbContext.userRoles.FirstOrDefault(x => x.RoleName == "Customer").RoleId;
            user.Status = true;
            _dbContext.users.Add(user);

            // Add Cart for new User
            var cart = new Cart();
            cart.UserId = user.UserId;
            _dbContext.carts.Add(cart);
            _dbContext.SaveChanges();

            return RedirectToAction("Login");
        }
    }
}

AppView/Views/Access/Login.cshtml
@model AppData.Models.User
@{
    ViewData["Title"] = "Đăng nhập";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="border: solid 2px darkblue; border-radius: 15px; margin-top: 50px;">
    <h1 style="text-align: center; font-weight: bold; color: white; background-color: darkblue; padding-top: 10px; padding-bottom: 10px; border-radius: 10px 10px 0px 0px;">ĐĂNG NHẬP</h1>

    <div style="width: 500px; margin: 50px auto;">
        @using (Html.BeginForm("Login", "Access", FormMethod.Post))
        {
            <div class="form-group">
                @Html.TextBoxFor(x => x.Email, new {@class = "form-control form-control-lg", placeholder="Email", required="required", autofocus="autofocus"})
            </div>
            <div class="form-group">
                @Html.TextBoxFor(x => x.Password, new {@class = "form-control form-control-lg", type="password", placeholder="Password"})
            </div>
            <div class="mt-3" style="text-align: center;">
                <button class="btn btn-block btn-gradient-primary btn-lg font-weight-medium auth-form-btn" type="submit"
                        style="border-radius: 10px; background-color: darkblue; color: white; font-weight: bold; width: 200px; margin-top: 30px;">
                    ĐĂNG NHẬP
                </button>
            </div>
            <div class="text-center" style="margin-top: 30px;">
                <p>Chưa có tài khoản? 
                    <a asp-controller="Access" asp-action="Register" style="text-decoration: none; font-weight: bold; color: red">ĐĂNG KÝ NGAY</a>
                </p>
                <p>hoặc đăng nhập bằng:</p>
                <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="bi-facebook"></i>
                </button>

                <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="bi-google"></i>
                </button>

                <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="bi-twitter"></i>
                </button>

                <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="bi-instagram"></i>
                </button>
            </div>
        }
    </div>

</div>

AppView/Views/Access/Register.cshtml
@model AppData.Models.User

@{
    ViewData["Title"] = "Đăng ký tài khoản";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="border: solid 2px darkblue; border-radius: 15px; margin-top: 50px;">
    <h1 style="text-align: center; font-weight: bold; color: white; background-color: darkblue; padding-top: 10px; padding-bottom: 10px; border-radius: 10px 10px 0px 0px;">ĐĂNG KÝ</h1>
    <div style="margin: auto">
        <form asp-action="Register" style="width: 500px; margin: 50px auto;">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Email" class="form-control" placeholder="Email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input id="matKhau" asp-for="Password" class="form-control" type="password" placeholder="Mật khẩu"/>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input id="xacNhanMK" class="form-control" type="password" placeholder="Xác nhận mật khẩu" onmouseout="CheckMK()"/>
                <span id="checkXacNhanMK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Name" class="form-control" placeholder="Họ và tên"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="PhoneNumber" class="form-control" placeholder="Số điện thoại"/>
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-check d-flex mb-5">
                <input class="form-check-input me-2" type="checkbox" value="" id="accept" onchange="ChangeCheck()"/>
                <label class="form-check-label" for="form2Example3">
                    Tôi đồng ý với tất cả  <a href="#!" style="text-decoration: none; color: darkblue; font-weight: bold">điều khoản dịch vụ</a>
                </label>
            </div>
            <div class="form-group" style="text-align: center">
                <button id="buttonSubmit" class="btn btn-block btn-gradient-primary btn-lg font-weight-medium auth-form-btn" type="submit"
                        style="border-radius: 10px; background-color: gray; color: white; font-weight: bold; width: 200px;" disabled>
                    ĐĂNG KÝ
                </button>
            </div>

            <script>
                var check = document.getElementById("accept");
                var button = document.getElementById("buttonSubmit");
                function ChangeCheck(){
                    if (check.checked) {
                        button.style.backgroundColor = "darkblue";
                        button.disabled = false;
                    } else {
                        button.style.backgroundColor = "gray";
                        button.disabled = true;
                    }
                }

                function CheckMK(){
                    var matKhau = document.getElementById("matKhau").value;
                    var xacNhanMK = document.getElementById("xacNhanMK").value;
                    var checkXacNhanMK = document.getElementById("checkXacNhanMK");
                    if(matKhau != xacNhanMK){
                        checkXacNhanMK.innerHTML = "*Xác nhận mật khẩu không chính xác";
                    }else{
                        checkXacNhanMK.innerHTML = "";
                    }
                }
            </script>
        </form>
    </div>
</div>

<div style="margin-top: 30px;">
    <a asp-controller="Access" asp-action="Login">
        <button style="border: none; border-radius: 5px; color: white; background-color: darkblue; font-weight: bold; padding: 5px 20px;">
            &#8592; Trở lại
        </button>
    </a>
</div>