AppView/Controllers/BillController.cs
using AppData.DBContext;
using AppData.Models;
using AppView.Services;
using AppView.Utilities;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using static System.Net.WebRequestMethods;

namespace AppView.Controllers
{
    public class BillController : Controller
    {
        private readonly ILogger<BillController> _logger;
        BookShopDbContext _dbContext;
        HttpClient _httpClient;
        public BillController(ILogger<BillController> logger)
        {
            _logger = logger;
            _httpClient = new HttpClient();
            _dbContext = new BookShopDbContext();
        }

        [HttpPost("/Bill/Purchase")]
        [ValidateAntiForgeryToken]
        //Một thuộc tính trong ASP.NET Core có tác dụng
        //như một biện pháp bảo mật khi post dữ liệu lên
        public IActionResult Purchase([Bind("Id, BookId, Quantity, UserId")] CartDetail cartDetail)
        {
            Bill bill = new Bill();
            bill.Id = Guid.NewGuid();
            bill.BillCode = "HD" + Utility.GenerateRandomString(4);
            bill.UserId = cartDetail.UserId;
            bill.CreateDate = DateTime.Now;
            bill.Status = 1;
            bill.TotalPrice = 0;
            _dbContext.bills.Add(bill);

            var cartDetails = new List<CartDetail>();
            if (HttpContext.Session.GetString("UserName") == null)
            {
                cartDetails = SessionServices.GetObjFromSession(HttpContext.Session, "Cart");
            }
            else
            {
                cartDetails = _dbContext.cartsDetails.Where(x => x.UserId.ToString() ==
                HttpContext.Session.GetString("UserId")).ToList();
            }

            foreach (var item in cartDetails)
            {
                BillDetail bd = new BillDetail();
                bd.Id = Guid.NewGuid();
                bd.BookId = item.BookId;
                bd.BillId = bill.Id;
                bd.Quantity = item.Quantity;
                bd.Price = _dbContext.books.ToList().FirstOrDefault(x => x.Id == item.BookId).Price;
                _dbContext.billsDetails.Add(bd);

                bill.TotalPrice += bd.Price * bd.Quantity;

                var sp = _dbContext.books.ToList().FirstOrDefault(x => x.Id == item.BookId);
                sp.AvailableQuantity -= item.Quantity;
                sp.NumberOfPurchase += item.Quantity;
                if (sp.AvailableQuantity <= 0)
                {
                    sp.Status = false;
                }
                _dbContext.books.Update(sp);
            }
            _dbContext.SaveChanges();

            if (HttpContext.Session.GetString("UserName") == null)
            {
                HttpContext.Session.Remove("Cart");

                string billsInCookie = "";
                billsInCookie = Request.Cookies["BillCookie"];
                if (billsInCookie == "" || billsInCookie == null)
                {
                    billsInCookie = bill.BillCode;
                }
                else
                {
                    billsInCookie = billsInCookie + "-" + bill.BillCode;
                }
                CookieOptions options = new CookieOptions();
                // Gộp danh sách mã HD thành 1 string dạng "BillCode1-BillCode2-..."
                Response.Cookies.Append("BillCookie", billsInCookie, options);
                // Lưu string chứa danh sách mã HD trên vào cookie
            }
            else
            {
                 var lstCD = _dbContext.cartsDetails.Where(x => x.UserId.ToString() ==
                HttpContext.Session.GetString("UserId")).ToList();
                foreach (var item in lstCD)
                {
                    _dbContext.cartsDetails.Remove(item);
                    _dbContext.SaveChanges();
                }
            }

            return RedirectToAction("ShowAllBills");
        }

        [HttpGet]
        public async Task<IActionResult> ShowAllBills()
        {
            List<Bill> showBills = new List<Bill>();

            if (HttpContext.Session.GetString("UserName") == null)
            {
                string billsInCookie = Request.Cookies["BillCookie"];
                if (billsInCookie != null && billsInCookie != "")
                {
                    string[] lstBills = billsInCookie.Split("-"); // Lấy ra từng mã hóa đơn ở cookie

                    var api = "https://localhost:7287/api/Bill";
                    var res = await _httpClient.GetFromJsonAsync<List<Bill>>(api); // Lấy danh sách hóa đơn từ API

                    foreach (var item in lstBills)
                    {
                        var billInAPI = res.FirstOrDefault(x => x.BillCode == item);
                        showBills.Add(billInAPI);
                    }
                }
            }
            else
            {
                showBills = _dbContext.bills.Where(x => x.UserId.ToString() == HttpContext.Session.GetString("UserId")).ToList();
            }
            return View(showBills);
        }

        public IActionResult Delete(Guid id)
        {
            var bill = _dbContext.bills.ToList().FirstOrDefault(x => x.Id == id);
            bill.Status = 0;
            
            var billDetails = _dbContext.billsDetails.ToList().Where(x => x.BillId == id);
            foreach(var item in billDetails)
            {
                var book = _dbContext.books.ToList().FirstOrDefault(x => x.Id == item.BookId);
                book.AvailableQuantity += item.Quantity;
                book.NumberOfPurchase -= item.Quantity; 
                if(book.Status == false)
                {
                    book.Status = true;
                }
                _dbContext.books.Update(book);
            }

            _dbContext.SaveChanges();
            return RedirectToAction("ShowAllBills");
        }

        public IActionResult GoodsReceived(Guid id)
        {
            var bill = _dbContext.bills.ToList().FirstOrDefault(x => x.Id == id);
            bill.Status = 3;
            _dbContext.bills.Update(bill);
            _dbContext.SaveChanges();
            return RedirectToAction("ShowAllBills");
        }
        public async Task<IActionResult> BillDetails(Guid id)
        {
            var api = "https://localhost:7287/api/BillDetail";
            var res = await _httpClient.GetFromJsonAsync<List<BillDetail>>(api);
            List<BillDetail> lstBillDetails = res.Where(x => x.BillId == id).ToList();
            ViewBag.Code = _dbContext.bills.FirstOrDefault(x => x.Id == id).BillCode;
            ViewBag.TotalPrice = _dbContext.bills.FirstOrDefault(x => x.Id == id).TotalPrice;
            ViewBag.Books = _dbContext.books.ToList();
            return View(lstBillDetails);
        }
    }
}

AppView/Views/Bill/BillDetails.cshtml
@using AppData.Models;
@using AppData.DBContext;
@using Microsoft.AspNetCore.Http;
@model IEnumerable<AppData.Models.BillDetail>

@{
    ViewData["Title"] = "Chi tiết hóa đơn";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int stt = 1;
    string maHD = ViewBag.Code;
    int totalPrice = ViewBag.TotalPrice;
    string totalPriceString = String.Format("{0:#,##0.##}", totalPrice);
    List<Book> lstBooks = ViewBag.Books;
}

<h1 style="text-align: center; font-weight: bold; margin-top: 50px; color: white; background-color: darkblue; padding-top: 10px; padding-bottom: 10px;">CHI TIẾT HÓA ĐƠN @maHD</h1>

@if(Model != null && Model.Count() > 0)
{
    <table class="table" style="margin-top: 30px;">
        <thead>
            <tr>
                <th style="text-align: center">STT</th>
                <th style="text-align: center">Tên sản phẩm</th>
                <th style="text-align: center">Số lượng mua</th>
                <th style="text-align: center">Giá tiền</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td style="text-align: center">
                        @(stt++)
                    </td>
                    <td style="text-align: center">
                        @lstBooks.FirstOrDefault(x => x.Id == item.BookId).Name
                    </td>
                    <td style="text-align: center">
                        @item.Quantity
                    </td>
                    <td style="text-align: center">
                        @String.Format("{0:#,##0.##}", item.Price) VNĐ
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div class="row" style="margin-top: 50px;">
        <div class="col-md-6">
            <a asp-action="ShowAllBills">
                <button style="border: none; border-radius: 5px; color: white; background-color: darkblue; font-weight: bold; padding: 5px 20px;">
                    &#8592; Trở lại
                </button>
            </a>
        </div>
        <div class="col-md-6">
            <h4 style="text-align: right; font-weight: bold; color: darkblue">Tổng tiền: </h4>
            <h3 style="text-align: right; font-weight: bold; color: red; margin-top: 10px;">@totalPriceString VNĐ </h3>
        </div>
    </div>
}

    
    

AppView/Views/Bill/ShowAllBills.cshtml
@using AppData.Models
@model IEnumerable<AppData.Models.Bill>

@{
    ViewData["Title"] = "Danh sách hóa đơn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 style="text-align: center; font-weight: bold; margin-top: 50px; color: white; background-color: darkblue; padding-top: 10px; padding-bottom: 10px;">DANH SÁCH HÓA ĐƠN</h1>

@{
    List<Bill> billChoXacNhan = Model.Where(x => x.Status == 1).ToList();
    List<Bill> billDangGiao = Model.Where(x => x.Status == 2).ToList();
    List<Bill> billThanhCong = Model.Where(x => x.Status == 3).ToList();
    List<Bill> billDaHuy = Model.Where(x => x.Status == 0).ToList();
}

@if (Model != null && Model.Count() > 0)
{
    <table class="table" style="margin-top: 30px;">
        <thead>
            <tr>
                <th style="text-align: center">
                    Mã hóa đơn
                </th>
                <th style="text-align: center">
                    Ngày mua
                </th>
                <th style="text-align: center">
                    Tổng tiền
                </th>
                <th style="text-align: center">
                    Tình trạng
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in billChoXacNhan)
            {
                <tr>
                    <td style="text-align: center">
                        @Html.DisplayFor(modelItem => item.BillCode)
                    </td>
                    <td style="text-align: center">
                        @Html.DisplayFor(modelItem => item.CreateDate)
                    </td>
                    <td style="text-align: center">
                        @String.Format("{0:#,##0.##}", item.TotalPrice) VNĐ
                    </td>
                    <td style="text-align: center">Chờ xác nhận</td>
                    <td style="width: 350px; text-align: center;">
                        <div class="row">
                            <div class="col-md-4">
                            </div>
                            <div class="col-md-4">
                                @using (Html.BeginForm("BillDetails", "Bill", new { id = item.Id }))
                                {
                                    <input type="hidden" value="@item.Id" name="id" />
                                    <input type="submit" value="Chi tiết" class="btn btn-primary" style="font-weight: bold; width: 100px;" />
                                }
                            </div>
                            <div class="col-md-4">
                                @using (Html.BeginForm("Delete", "Bill", new { id = item.Id }))
                                {
                                    <input type="hidden" value="@item.Id" name="id" />
                                    <input type="submit" value="Hủy đơn" class="btn btn-primary" style="font-weight: bold; width: 100px;" />
                                }
                            </div>
                        </div>
                    </td>
                </tr>
            }
            @foreach (var item in billDangGiao)
            {
                <tr>
                    <td style="text-align: center">
                        @Html.DisplayFor(modelItem => item.BillCode)
                    </td>
                    <td style="text-align: center">
                        @Html.DisplayFor(modelItem => item.CreateDate)
                    </td>
                    <td style="text-align: center">
                        @String.Format("{0:#,##0.##}", item.TotalPrice) VNĐ
                    </td>
                    <td style="text-align: center">Đang giao hàng</td>
                    <td style="width: 350px; text-align: center;">
                        <div class="row">
                            <div class="col-md-4">
                                @using (Html.BeginForm("GoodsReceived", "Bill", new { id = item.Id }))
                                {
                                    <input type="hidden" value="@item.Id" name="id" />
                                    <input type="submit" value="Đã nhận" class="btn btn-primary" style="font-weight: bold; width: 100px;" />
                                }
                            </div>
                            <div class="col-md-4">
                                @using (Html.BeginForm("BillDetails", "Bill", new { id = item.Id }))
                                {
                                    <input type="hidden" value="@item.Id" name="id" />
                                    <input type="submit" value="Chi tiết" class="btn btn-primary" style="font-weight: bold; width: 100px;" />
                                }
                            </div>
                            <div class="col-md-4">
                                @using (Html.BeginForm("Delete", "Bill", new { id = item.Id }))
                                {
                                    <input type="hidden" value="@item.Id" name="id" />
                                    <input type="submit" value="Hủy đơn" class="btn btn-primary" style="font-weight: bold; width: 100px;" />
                                }
                            </div>
                        </div>
                    </td>
                </tr>
            }
            @foreach (var item in billThanhCong)
            {
                <tr>
                    <td style="text-align: center">
                        @Html.DisplayFor(modelItem => item.BillCode)
                    </td>
                    <td style="text-align: center">
                        @Html.DisplayFor(modelItem => item.CreateDate)
                    </td>
                    <td style="text-align: center">
                        @String.Format("{0:#,##0.##}", item.TotalPrice) VNĐ
                    </td>
                    <td style="text-align: center">Giao hàng thành công</td>
                    <td style="width: 350px; text-align: center;">
                        <div class="row">
                            <div class="col-md-4">
                            </div>
                            <div class="col-md-4">
                                @using (Html.BeginForm("BillDetails", "Bill", new { id = item.Id }))
                                {
                                    <input type="hidden" value="@item.Id" name="id" />
                                    <input type="submit" value="Chi tiết" class="btn btn-primary" style="font-weight: bold; width: 100px;" />
                                }
                            </div>
                            <div class="col-md-4">
                            </div>
                        </div>
                    </td>
                </tr>
            }
            @foreach (var item in billDaHuy)
            {
                <tr>
                    <td style="text-align: center">
                        @Html.DisplayFor(modelItem => item.BillCode)
                    </td>
                    <td style="text-align: center">
                        @Html.DisplayFor(modelItem => item.CreateDate)
                    </td>
                    <td style="text-align: center">
                        @String.Format("{0:#,##0.##}", item.TotalPrice) VNĐ
                    </td>
                    <td style="text-align: center">Đã hủy đơn</td>
                    <td style="width: 350px; text-align: center;">
                        <div class="row">
                            <div class="col-md-4">
                            </div>
                            <div class="col-md-4">
                                @using (Html.BeginForm("BillDetails", "Bill", new { id = item.Id }))
                                {
                                    <input type="hidden" value="@item.Id" name="id" />
                                    <input type="submit" value="Chi tiết" class="btn btn-primary" style="font-weight: bold; width: 100px;" />
                                }
                            </div>
                            <div class="col-md-4">
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h3 style="text-align: center; font-weight: bold; color: darkblue; margin-top: 30px;">Hiện không có hóa đơn nào!</h3>
}